driver:
  require_chef_omnibus: <%= ENV.fetch("CHEF_VERSION", "latest") %>
  ssh_key: <%= File.expand_path("./test/support/keys/vagrant") %>
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.4
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.5
    run_list:
      - recipe[yum-epel]
  - name: fedora-20

suites:
  - name: default
    run_list:
      - recipe[monit]
  - name: source
    run_list:
      - recipe[monit]
    attributes:
      monit:
        source_install: true
  - name: binary
    run_list:
      - recipe[monit]
    attributes:
      monit:
        binary_install: true
