language: ruby
bundler_args: --without integration
rvm:
- 2.0.0
- 2.1.6
- 2.2.2
script:
- bundle exec rake rubocop
- bundle exec rake foodcritic
- bundle exec rake chefspec
- bundle exec rake kitchen:all
env:
  matrix:
  - CHEF_VERSION: "10.30"
  - CHEF_VERSION: "11.10"
